### ISSUE TITLE
Rewrite... again

### ISSUE THREAD

**Issue by TRIDENT1313** [ForeverAndEverTeam/fae-mod#105]
So considering how much drama this thing has caused, I think a re-write might not be an awful idea.
When I considered how much they let us use, I want to reduce it down a ton, by half at least.

Bonus points if I can do it without breaking a persistent file.

### Things that won't be changed:
- Chat class thing (Too much work to re-do and will break everything.
- Topic related stuff
- Topic call
### Things I'd like to re-do
- Sky/weather
- Rooms
- Calendar (I want to make a new calendar. We have assets for it, so maybe I can do something with it.)
- Backup system (I liked the backup system "we" had. If I can make another one, I might be able to prevent broken persistents with more ease)
- Affection (Same rate of unlock, just a new class with new functions and do it... betterer

### Maybes:
- Chat class (granted this probably won't ever happen, but mayyyybeeee in future
- Gifting but.. good (the way it is now... well it kinda sucks. I'd really like to make a proper gifting system with json files and all that, but parsing json is a pain in the ass.)
- Time travel detection (Would be nice. Would add immersion. Will be frustrating to do.)

I think that covers just about everything.
I'll update this post as I think of more stuff

**Comment by Blizzardsev** [comment]
A little late to the party so I apologize, but some thoughts.

I would personally struggle to see the value of a re-write here: FaE already has permissions for the systems in use after all, so reinventing the wheel on those for the sake of a situation that has already been resolved doesn't seem like grounds for effectively starting over on core mechanics - and from a third party perspective, I can see it being wasteful to go over the review process, etc. if the work used isn't going to be used _anyway_.

I think it's worth bearing in mind too that:

- These systems are tried and tested, with most issues already ironed out - the investment for these in terms of dev time and testing has already been paid too! Why pay the same costs twice?
- These systems will be a known quantity to potential contributors from other mods: switching to brand new systems means potential contributors having to learn even more bespoke code, and onboarding these kinds of projects can already be tricky.
- Bugs already seem to be a challenge for FaE: is a rewrite for the reasons you gave worth the risk of more?
- How will data be transferred from system to system? Does FaE have migration systems to handle this sort of thing?

Of course I'm not saying there isn't room for improvement with these systems, but I'd highly suggest rethinking this one before going neck-deep into changes. Remember, all the effort spent on something like this is time and energy that could be spent building up instead of starting again!

**Comment by ashyashton** [comment]
First: Please tell me you mean on FIRST startup, not on every startup. As someone who is aware of that fact, I don't need to be annoyed with a reminder every time I open the mod.

Second: "I don't want our userbase to become as mentally ill" is awful phrasing. Mental issues are demonized enough without you adding onto it. I would think you'd know that since Sayori, who _is_ mentally ill, happens to be the one you're making a mod for. "Obsessive" would probably be a better phrase, one that doesn't imply mental illness is just some random little thing that pops up because you played a game with a cute girl as opposed to being a serious, underlying issue that needs careful treatment.

**Comment by TRIDENT1313** [comment]
This ain't happening and I guess it was foolish to think it would...

Maybe if someone else does their own Just Sayori mod, they can re-write it.

Anyway, closing.
